
services:
  - type: web
    name: secure-api
    env: python
    buildCommand: pip install -r requirements.txt && flask db init || true && flask db migrate -m "auto" || true
    startCommand: gunicorn run:app --worker-class gevent --workers 2
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: secure-api-db
          property: connectionString
          value: postgre:///secure-api-db
      - key: FLASK_ENV
        value: production

databases:
  - name: secure-api-db
    plan: free
